FROM cgr.dev/chainguard/python:latest-dev as builder

ENV LANG=C.UTF-8
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PATH="/gary-tarot/venv/bin:$PATH"

WORKDIR /gary-tarot

RUN python -m venv /gary-tarot/venv
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

FROM cgr.dev/chainguard/python:latest

WORKDIR /gary-tarot

ENV PYTHONUNBUFFERED=1
ENV PATH="/venv/bin:$PATH"

COPY app.py ./
COPY static/ ./static
COPY templates/ ./templates
COPY --from=builder /gary-tarot/venv /venv

EXPOSE 5000

ENTRYPOINT [ "python", "/gary-tarot/app.py" ]