FROM cgr.dev/chainguard/wolfi-base

ARG version=3.12
WORKDIR /gary-tarot

RUN apk add python-${version} py${version}-pip && \
	chown -R nonroot.nonroot /gary-tarot/

USER nonroot
COPY requirements.txt app.py /gary-tarot/
COPY static/ /gary-tarot/static
COPY templates/ /gary-tarot/templates
RUN  pip install -r requirements.txt --user

EXPOSE 5000

ENTRYPOINT [ "python", "/gary-tarot/app.py" ]
